### ISSUE TITLE
Will IperfCsvRunner UDP result calculate in flent-gui?

### ISSUE THREAD

**Issue by mlouielu** [tohojo/flent#136]
For what I saw is, it will not store the `MEAN_VALUE` when the runner finish.

But the `raw_value` were recorded. Why will not gui calculate the mean value when loading the plot?

**Comment by tohojo** [comment]
Louie Lu <notifications@github.com> writes:

> For what I saw is, it will not store the `MEAN_VALUE` when the runner
> finish.

This is probably because you are not getting a reply from the server.
Either because no iperf -us is running on your target host, or because
the packet with the results is getting lost.

> But the `raw_value` were recorded. Why will not gui calculate the mean
> value when loading the plot?

The data point that are emitted during the test are basically
meaningless for UDP tests. They just reflect at which bandwidth the
transmitter is sending; half of those could be getting lost and you
wouldn't know from the data points. This is why I removed all the plots
with those values, as they are liable to mislead. So the only plot that
you can get from the UDP tests is the MEAN_VALUE, which is the value
reported back from the server. If that's getting lost you won't see
anything, so you should investigate why they are :)

-Toke
