### ISSUE TITLE
Better color selection for graphs

### ISSUE THREAD

**Issue by dtaht** [tohojo/flent#14]
some graphs use a combination of orange, red, and greenish blue that is kind of hard to see. The one bugging me at the moment is the total bandwidth and average ping plot in rrul. I like ping in red. I think the orange should be green, the greenish blue, blue....

I am totally hopeless for color selections, it is my hope that someone with an artistic bent shows up and reviews the plot types for better color matches and patterns....

**Comment by tohojo** [comment]
Do any of the colour schemes on http://colorbrewer2.org/ look better to you?

**Comment by shemminger** [comment]
A couple of points:
* make sure you choose varying levels of darkness because some people are color blind
http://www.color-blindness.com/2007/06/02/how-to-color-charts-respecting-color-blindness/
* color theory is a deep subject, but using some form of complimentary colors highlights things:
http://creativepro.com/learning-to-use-color-your-web-site/
