### ISSUE TITLE
-D option and /tmp default breaks std unix semantics

### ISSUE THREAD

**Issue by dtaht** [tohojo/flent#42]
All other unix derived tools drop their files in the local directory by default.

-D somewhere_else is ok, way to set that as a default is good in the rcfile, but the default behavior should be the local dir, (and my beef with the gui is that should default to saving out also to the local dir)

There are a zillion things wrong with the idea of dropping files into tmp by default. More than one user using the tool at the same time. Using a dirname as the basic means of distinguishing between test runs and having shorter filenames as a result. Having to move stuff from tmp to somewhere else...

and... 

Breaking the most common semantic for unix... 

Sure: use /tmp to store a temporary file, but not the final output. (but that is handled by grabbing the std TMPDIR env var from the environment)

**Comment by tohojo** [comment]
Well, my thought was that for one-off tests you'd not necessarily want
to store the data file (I certainly have weird one-off test files
littered all over the place). And that if you did want to store it
permanently you'd move it manually (that's why Flent now tells you where
the file is unconditionally), or use the -D / rcfile.

An alternative could be to have a ~/.flent and store files there by default?

**Comment by dtaht** [comment]
one-off-going-directly-to-gui maybe. but elsewhere no.

and moving it manually is a pta when it gets mixed with other(s) stuff. far better to default to the . as before.

**Comment by tohojo** [comment]
*sigh*, okay, reverting to the old behaviour...
