### ISSUE TITLE
using shorter step sizes has issues --step-size=.02

### ISSUE THREAD

**Issue by dtaht** [tohojo/flent#43]
This captures a very fine grain of detail that is satisfying on shorter RTTs especially (this is a 10ms path)

http://snapon.lab.bufferbloat.net/~cero3/shortened_step_size_bug/shortened_stepsize_bug.svg

but the ping and udp flows last too long.

**Comment by dtaht** [comment]
Relevant data is also in that dir.

**Comment by dtaht** [comment]
This bug appears not to occur using normal ping. I can, as a user, use --step-size=.02 instead of the default .2 and the tests run correctly.  However with fping, they are wrong.

see: http://snapon.cs.kau.se/~d/bug1/ for the two runs.

**Comment by tohojo** [comment]
Dave Täht <notifications@github.com> writes:

> This bug appears not to occur using normal ping. I can, as a user, use
> - -step-size=.02 instead of the default .2 and the tests run
> correctly. However with fping, they are wrong.
>
> see: http://snapon.cs.kau.se/~d/bug1/ for the two runs.

Right, I think this is a timing issue in fping. My cursory testing
indicates that it can't keep up with an interval shorter than ~25 ms.
And since you can't specify a total run-time in fping (but only a number
of pings), this affects the total runtime.

A solution could be to just forcefully kill fping if it's running long;
I'll think about whether that is a good idea. In the meantime, try
intervals of 25 or 30 ms and see if that works better :)

Normal 'ping' can't keep up either on my box, BTW, but that just results
in fewer ping packets being transmitted, not in the test running long.

-Toke
