### ISSUE TITLE
symbolic link to /usr/local/bin/flent on osx?

### ISSUE THREAD

**Issue by dtaht** [tohojo/flent#46]
/opt/local/Library/Frameworks/Python.framework/Versions/3.4/bin/flent-gui *.flent.gz

is a tad long. Is there a way to convince setup.py install to put something in the path?

I was pleased to see python3.4 setup.py install work at all on osx, actually.

**Comment by tohojo** [comment]
> /opt/local/Library/Frameworks/Python.framework/Versions/3.4/bin/flent-gui
> *.flent.gz
>
> is a tad long. Is there a way to convince setup.py install to put
> something in the path?

No idea. You can try playing around with options to `setup.py install`.
There's at least a --root parameter which might work. Maybe adding
--single-version-externally-managed is needed as well.

Or you could, yaknow, update $PATH? :)


> I was pleased to see python3.4 setup.py install work at all on osx,
> actually.

Well I run python3.4 myself, so that probably gets the most testing :)
